### ISSUE TITLE
Document URM steps to work with AL2

### ISSUE THREAD

**Issue by sharad-oss** [awslabs/amazon-emr-user-role-mapper#2]
Current installation steps work on AL1 hardware. We need to change the script to work for any hardware type.

**Comment by jbenninghoff** [comment]
This is the stderr message when attempting URM bootstrap on EMR v5.31 (AL2 and systemd based AMI):

+ sudo aws s3 cp s3://jobennin-uip-configs/urm/emr-user-role-mapper.conf /etc/init/
+ echo 'Reload config'
+ sudo initctl reload-configuration
sudo: initctl: command not found

**Comment by sharad-oss** [comment]
Fixed with [this](https://github.com/awslabs/amazon-emr-user-role-mapper/pull/13) commit.
