### ISSUE TITLE
AWS Credentials now required in EMR

### ISSUE THREAD

**Issue by jbenninghoff** [awslabs/amazon-emr-user-role-mapper#27]
AWS Credentials are now required in EMR/beeline even for the hadoop account unlike previous URM release.

hadoop@ip-172-31-23-113 8C/30G$ beeline -u $bee_auth <<< "create external table jnk(a string, b string) row format delimited fields terminated by ',' location 's3a://jobennin-sf-tables/tmp/jnk';"
Connecting to jdbc:hive2://ip-172-31-23-113.us-west-2.compute.internal:10000/default;principal=hive/ip-172-31-23-113.us-west-2.compute.internal@EC2.INTERNAL;auth=kerberos;ssl=true;sslTrustStore=/usr/share/aws/emr/security/conf/truststore.jks;trustStorePassword=xxxxxxxxxx
Connected to: Apache Hive (version 2.3.7-amzn-1)
Driver: Hive JDBC (version 2.3.7-amzn-1)
Transaction isolation: TRANSACTION_REPEATABLE_READ
Beeline version 2.3.7-amzn-1 by Apache Hive
0: jdbc:hive2://ip-172-31-23-113.us-west-2.co> create external table jnk(a string, b string) row format delimited fields terminated by ',' location 's3a://jobennin-sf-tables/tmp/jnk';
INFO  : Compiling command(queryId=hive_20210105215649_39c6a56e-e91f-4d62-a5c0-79f95f4311d6): create external table jnk(a string, b string) row format delimited fields terminated by ',' location 's3a://jobennin-sf-tables/tmp/jnk'
INFO  : Semantic Analysis Completed
INFO  : Returning Hive schema: Schema(fieldSchemas:null, properties:null)
INFO  : Completed compiling command(queryId=hive_20210105215649_39c6a56e-e91f-4d62-a5c0-79f95f4311d6); Time taken: 0.078 seconds
INFO  : Concurrency mode is disabled, not creating a lock manager
INFO  : Executing command(queryId=hive_20210105215649_39c6a56e-e91f-4d62-a5c0-79f95f4311d6): create external table jnk(a string, b string) row format delimited fields terminated by ',' location 's3a://jobennin-sf-tables/tmp/jnk'
INFO  : Starting task [Stage-0:DDL] in serial mode
ERROR : FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. MetaException(message:org.apache.hadoop.fs.s3a.AWSClientIOException: doesBucketExist on jobennin-sf-tables: com.amazonaws.AmazonClientException: **No AWS Credentials provided by BasicAWSCredentialsProvider EnvironmentVariableCredentialsProvider InstanceProfileCredentialsProvider** : com.amazonaws.AmazonServiceException: No Content (Service: null; Status Code: 204; Error Code: null; Request ID: null; Proxy: null): No AWS Credentials provided by BasicAWSCredentialsProvider EnvironmentVariableCredentialsProvider InstanceProfileCredentialsProvider : com.amazonaws.AmazonServiceException: No Content (Service: null; Status Code: 204; Error Code: null; Request ID: null; Proxy: null))
INFO  : Completed executing command(queryId=hive_20210105215649_39c6a56e-e91f-4d62-a5c0-79f95f4311d6); Time taken: 0.04 seconds

This new requirement won't work with federated users.

**Comment by sharad-oss** [comment]
Which EMR release version causes this? Can you validate that aws cli works for hadoop user? Hadoop user should not be intercepted by URM.

**Comment by jbenninghoff** [comment]
EMR v5.31

Yes, there a few CLI commands before the beeline create table in my smoke test.  Beeline 'show tables;' works just fine.
Here is an example AWS CLI from that cluster, which is still running if you want to take a look first hand:

hadoop@ip-172-31-23-113 8C/30G$ aws s3 ls s3://jobennin-sf-tables/tmp/
2020-05-19 18:33:48          0
2021-01-05 20:50:16       8004 hadoop-tests.sh

**Comment by hocanint-amzn** [comment]
The hive user needs to have a mapping since hive commands run within HiveServer2/HiveMetaStore as the Hive user. This is even with hive.server2.enable.doAs enabled. We should update the README with these instructions.

**Comment by sharad-oss** [comment]
Closing this old issue.
