### ISSUE TITLE
URM credential provider's AWSCredentialsProviderChain fallback to InstanceProfileCredentialsProvider 

### ISSUE THREAD

**Issue by sunyulin728** [awslabs/amazon-emr-user-role-mapper#47]
When URM credential provider can't get credential from URM service, for example, timeout or no permission to impersonate user, it will fallback to InstanceProfileCredentialsProvider. And then it will get the EC2 machine's credential which might has full permission.

**Comment by sharad-oss** [comment]
That call will not go to IMDS. The call will be handled by URM. Not an issue - closing.
