### ISSUE TITLE
Fallback to global STS when the regional STS service is not available

### ISSUE THREAD

**Issue by sunyulin728** [awslabs/amazon-emr-user-role-mapper#48]
We have met STS service unavailable issue when another service was sending much STS request. 

The current code is to choose either global STS or regional STS server. It will be better to add logic to take regional STS server as primary and fallback to global STS server when region STS service is not available.

**Comment by sharad-oss** [comment]
This adds unnecessary complexity and the plan is to deprecate global STS endpoint.
